Introduce AdMob banner adapter
prebid/prebid-mobile-android pull request #334
Opened 2021-12-24 11:41 UTC by ValentinPostindustria

Make flexible mediation delegate architecture. Rewrite MoPub adapters with new delegate. Fix eamples in rendering test app. Create AdMob banner example. #323

2021-12-24 14:18 UTC, ValentinPostindustria commented
MoPub check after applying new architecture. 
![изображение](https://user-images.githubusercontent.com/72038591/147358482-aa296c43-5720-4ba6-81b0-8e7b6352e9f1.png)
![изображение](https://user-images.githubusercontent.com/72038591/147358492-7fa7d918-8a1b-4ec9-9c14-459bc2a21856.png)
![изображение](https://user-images.githubusercontent.com/72038591/147358498-fa8759f0-aeb7-42ac-b77a-1c4c2ff54bfe.png)
![изображение](https://user-images.githubusercontent.com/72038591/147358503-a41f0e6d-879e-4e11-a4ad-35beaca62826.png)
![изображение](https://user-images.githubusercontent.com/72038591/147358509-d8cf2df4-939f-486f-8a17-c016c67592be.png)

2022-01-18 08:30 UTC, YuriyVelichkoPI requested changes
In general looks good. Need to correct behavior related to the autorefresh, please look at the attached comments

2022-01-18 08:30 UTC, YuriyVelichkoPI commented on PrebidMobile/PrebidMobile-admobAdapters/src/main/java/org/prebid/mobile/admob/AdMobBannerMediationUtils.java
> +        return true;
This method should return false if banner is not visible to the user

2022-01-18 08:30 UTC, YuriyVelichkoPI commented on PrebidMobile/PrebidMobile-mopubAdapters/src/main/java/com/mopub/mediation/MoPubBaseMediationUtils.java
> +        return true;
Its better to return `false` as a default behavior.

2022-01-19 09:01 UTC, YuriyVelichkoPI approved these changes
LGTM

2022-01-19 09:01 UTC, merged