Introduce AdMob native adapter
prebid/prebid-mobile-android pull request #342
Opened 2022-01-25 17:34 UTC by ValentinPostindustria

Create AdMob native adapter. Create examples in test apps. Fix NativeAsset error from Kotlin code. Closes #341.

2022-02-02 11:13 UTC, ValentinPostindustria commented
Closes #333.

2022-02-07 09:57 UTC, YuriyVelichkoPI requested changes

2022-02-07 09:57 UTC, YuriyVelichkoPI commented on PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidNativeAd.java
> +    @Nullable
We should keep the same API for existing properties. Need to remove `@Nullable` and return empty values. This is relevant to all properties.

2022-02-09 09:24 UTC, YuriyVelichkoPI approved these changes
LGTM

2022-02-09 09:24 UTC, merged