Shared Preferences fix
prebid/prebid-mobile-android pull request #506
Opened 2022-10-28 12:40 UTC by MaksPetrukhnoPI

2022-10-31 09:50 UTC, ValentinPostindustria approved these changes
LGTM!

2022-10-31 10:31 UTC, YuriyVelichkoPI requested changes

2022-10-31 10:31 UTC, YuriyVelichkoPI commented on PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/sdk/deviceData/managers/UserConsentManager.java
> +                } catch (ClassCastException classCastException) {
Need to polish the code here:
- Use curly brackets for if-else 
- Add a comment to the line where we try to extract the boolean value. Mention the bug in the comment
- wrap getBoolean into try-catch as well. Who knows what we can meet there. 
- keep the consistent formatting for `preferences.edit()` line - put each function on the separate row

2022-10-31 12:23 UTC, YuriyVelichkoPI approved these changes
LGTM

2022-11-01 09:36 UTC, ValentinPostindustria approved these changes
LGTM

2022-11-01 09:40 UTC, merged