Introduce SDK Configuration Properties for Creative Factory Timeout
prebid/prebid-mobile-android pull request #664
Opened 2023-08-10 17:54 UTC by jsligh

Introduced:
- `PrebidMobile.creativeFactoryTimeout` to customize `BANNER_TIMEOUT`.
- `PrebidMobile.creativeFactoryTimeoutPreRenderContent` to customize `INTERSTITIAL_TIMEOUT` and `VAST_TIMEOUT`.
- In `bidrequest.ext.prebid.passthrough` used `cftbanner` for `BANNER_TIMEOUT` and `cftprerender` for `INTERSTITIAL_TIMEOUT` and `VAST_TIMEOUT`
- Added conditions in `CreativeFactoryTest` and `MobileSdkPassThroughTest`

2023-08-15 09:54 UTC, ValentinPostindustria requested changes

2023-08-15 09:54 UTC, ValentinPostindustria commented on PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/models/openrtb/bidRequests/MobileSdkPassThrough.java
> +                getAndSave("cftprerender", Integer.class, it -> preRenderTimeout = it);
If a user set up only one configuration parameter this line will throw an exception. We should support cases with only one parameter.

2023-08-15 09:54 UTC, ValentinPostindustria commented on PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/models/openrtb/bidRequests/MobileSdkPassThrough.java
For now `MobileSdkPassThrough` will be created only if it contains `adconfiguration`. But publishers can set up only `sdkconfiguration` parameters, without `adconfiguration`.

2023-08-15 09:54 UTC, ValentinPostindustria commented on PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/models/openrtb/bidRequests/MobileSdkPassThroughTest.java
> +                    "{\"prebid\":{\"passthrough\":[{\"type\":\"prebidmobilesdk\",\"adconfiguration\":{\n\"ismuted\": false,\n\"maxvideoduration\": 15,\n\"closebuttonarea\": 0.3,\n\"closebuttonpositio
Remove `adconfiguration`, leave `sdkconfiguration` and the test must pass.

2023-08-15 09:54 UTC, ValentinPostindustria commented on PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/rendering/models/openrtb/bidRequests/MobileSdkPassThroughTest.java
> +            assertEquals((Integer) 7800, subject.bannerTimeout);
Add separated tests with only bannerTimeout and only preRenderTimeout in Json.

2023-08-15 13:51 UTC, ValentinPostindustria submitted a review, later dismissed

2023-08-16 08:09 UTC, YuriyVelichkoPI commented
Here is a task for adding the tests: https://github.com/prebid/prebid-mobile-autotests/issues/79

2023-08-16 08:14 UTC, YuriyVelichkoPI approved these changes
LGTM

2023-08-16 08:17 UTC, merged