added install instructions for Kotlin DSL
prebid/prebid-mobile-android pull request #718
Opened 2023-11-29 12:48 UTC by charlie-docwriter

I have added installation instructions for Kotlin DSL-based build scripts in addition to the existing Groovy-based instructions, as well as some text edits.

2024-01-03 17:03 UTC, jsligh approved these changes
Looks good to me, as long as you fix the merge conflicts!

2025-10-03 08:37 UTC, YuriyVelichkoPI commented
@mdanylov-sigma does this PR still make sense after the [migration](https://github.com/prebid/prebid-mobile-android/pull/890) ?

2025-10-03 08:48 UTC, mdanylov-sigma commented
> @mdanylov-sigma does this PR still make sense after the [migration](https://github.com/prebid/prebid-mobile-android/pull/890) ?

Yes, cause it contains only some text changes and alternative way to add the PrebidMobile as an dependency for publishers.

2025-10-03 11:18 UTC, mdanylov-sigma requested changes
Could you please resolve conflicts to merge this PR ?

2026-07-30 06:25 UTC, closed without merging