Impression tracker for original API
prebid/prebid-mobile-android pull request #804
Opened 2024-11-14 09:01 UTC by ValentinPostindustria

2024-11-20 09:38 UTC, YuriyVelichkoPI requested changes

2024-11-20 09:38 UTC, YuriyVelichkoPI commented on PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/AdUnit.java
> +                registerVisibilityTrackerIfNeeded(bidResponse);
This approach doesn't look reliable. Switching the tracker on/off for each result of the bid fetching may lead to gaps in tracking.

Let's implement it in the way introduced on iOS.

- start viewability tracking on calling of `activatePrebidImpressionTracker` 
- stop tracking on destroying the AdUnit object 
- once the tracked view meets the impression tracking criteria - check the content, and if it contains PUC - track the respective impression.

2024-11-20 09:38 UTC, YuriyVelichkoPI commented on PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/AdUnit.java
> +    protected WeakReference<View> adViewReference = new WeakReference<>(null);
Can we hold adViewReference in VisibilityMonitor?

2024-11-20 19:04 UTC, ValentinPostindustria commented
[Charles session](https://github.com/user-attachments/files/17835511/burl_tracking.zip).

2024-11-21 10:24 UTC, ValentinPostindustria commented
[Charles session with Mraid](https://github.com/user-attachments/files/17844060/burl_tracking_with_mraid.zip).

2025-02-10 09:57 UTC, YuriyVelichkoPI requested changes

2025-02-10 09:57 UTC, YuriyVelichkoPI commented on PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/AdUnit.java
> +        visibilityMonitor.stopTracking();
Is it safe that we stop tracking when we receive the bid? The SDK can get a new bid before the impression of the previous one?

2025-02-10 09:57 UTC, YuriyVelichkoPI commented on PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/AdUnit.java
> +        boolean isBannerTracker = !(this instanceof InterstitialAdUnit);
This code looks confusing. Please make the activation conditions more clear.

2025-02-10 09:57 UTC, YuriyVelichkoPI commented on Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/gam/original/GamOriginalInstreamNewApiFragment.kt
> -        adUnit?.stopAutoRefresh()
This change looks as potential memory leak. What if the publisher utilizes a new counting methodology and will not call `destroy()`?

2025-02-11 13:58 UTC, ValentinPostindustria commented on Example/PrebidInternalTestApp/src/main/java/org/prebid/mobile/renderingtestapp/plugplay/bidding/gam/original/GamOriginalInstreamNewApiFragment.kt
> -        adUnit?.stopAutoRefresh()
If a user uses this burl tracker, it's better to use destroy(). Otherwise the monitor will traverse view hierarchy as long as the ad view container exists.

2025-02-18 08:53 UTC, YuriyVelichkoPI approved these changes
LGTM

2025-02-18 08:53 UTC, merged

2025-02-18 08:57 UTC, YuriyVelichkoPI commented
The PUC still fires the `burl`. So we will create a follow-up ticket to support new imptrackers schema once it is ready.  For now publishers can customize the PUC in order not to track BURL if they want to use SDK native tracking. 

The default behavior is not changed. The SDK tracking is opt-in.